### ISSUE TITLE
Corners overlapping issue

### ISSUE THREAD

**Issue by vv-monsalve** [originaltype/kufam#10]
When reviewing some assets created for Kufam, there are visible some overlapping issues apparently caused by some corners on the font.
Inspecting the fonts, the issues are directly in the font files (both static and Variable) rather than a rendering issue on some app. 

**Bold**
![Screen Shot 2021-01-11 at 21 26 29](https://user-images.githubusercontent.com/48698976/104337221-3afdce80-54c3-11eb-8027-edf2c3726eb3.png)
**Black**
![Screen Shot 2021-01-11 at 21 27 06](https://user-images.githubusercontent.com/48698976/104337223-3c2efb80-54c3-11eb-9041-c31dca132721.png)

**Comment by vv-monsalve** [comment]
It is also happening in the `one` 

![Screen Shot 2021-01-11 at 19 55 18](https://user-images.githubusercontent.com/48698976/104341141-726e7a00-54c7-11eb-9517-4ef17255ce62.png)
![Screen Shot 2021-01-12 at 11 14 44](https://user-images.githubusercontent.com/48698976/104341158-769a9780-54c7-11eb-95db-a4289b7728bc.png)

**Comment by vv-monsalve** [comment]
I've found this [Issue](https://github.com/google/fonts/issues/2637) where other glyphs are mentioned FYI

**Comment by arturschmal** [comment]
Thank you! I have only just starting following the google/fonts repo recently so those issues have not reached me at the time.
