### ISSUE TITLE
New FB reported Fail: nested components

### ISSUE THREAD

**Issue by vv-monsalve** [originaltype/kufam#11]
This Fail was reported after performing new 0.7.34 FB version tests on latest font files in the repo, at commit 49b9656

<details>
<summary>🔥 <b>FAIL:</b> Check glyphs do not have components which are themselves components.</summary>

* [com.google.fonts/check/glyf_nested_components](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/glyf.html#com.google.fonts/check/glyf_nested_components)
<pre>--- Rationale ---

There have been bugs rendering variable fonts with nested components.
Additionally, some static fonts with nested components have been reported to
have rendering and printing issues.

For more info, see:
* https://github.com/googlefonts/fontbakery/issues/2961
* https://github.com/arrowtype/recursive/issues/412

</pre>

* 🔥 **FAIL** The following glyphs have components which themselves are component glyphs:
	* Aacute
	* Abreve
	* Acircumflex
	* Adieresis
	* uni1EA0
	* Agrave
	* Amacron
	* Aogonek
	* Aring
	* Aringacute and 330 more. [code: found-nested-components]

</details>

**Comment by arturschmal** [comment]
The solution is to decompose the nested components?

**Comment by vv-monsalve** [comment]
Yes, it would be the case. Component referring to another component are not exported correctly to the ttf variable format. They take back the coordinates of the original glyph. E.g. Issue [#2961](https://github.com/googlefonts/fontbakery/issues/2961)

Once you decompose them, please ensure they don't end up fractional coordinates also.

These verifications are related to our [Outline Quality Checklist](https://github.com/originaltype/kufam/issues/12).
In the new FB reports are also some Warns regarding this. Let me know if you would be willing to review them as part of this quick update process.

**Comment by arturschmal** [comment]
I have decomposed mark characters (such as .case and vietnamese diacritics) that were build as components and built new fonts but the report of FB test says there's still a lot of nested components left but it doesnt give the full list of characters. Is there a way to have FB print the full list of characters with nested components in them?

You can see the report in the the branch `kufam-fixes` in the sources folder.
🔥 FAIL
The following glyphs have components which themselves are component glyphs:
* uni01C6.sc
* uni01C4
* uni01C5
* uni01C6
* onequarter
* onequarter
* onehalf
* onehalf
* threequarters
* threequarters and 276 more. [code: found-nested-components]


The fontfile Kufam-Regular.ttf gives an error on almost every test with this ERROR message:

💥 ../Fonts/TTF/Kufam-Regular.ttf
💥 ERROR
The check <FontBakeryCheck:com.google.fonts/check/all_glyphs_have_codepoints> had an error: FailedConditionError: The condition <FontBakeryCondition:ttFont> had an error: TTLibError: Not a TrueType or OpenType font (not enough data)

**Comment by vv-monsalve** [comment]
> Is there a way to have FB print the full list of characters with nested components in them?

I uploaded to my QA-Kufam branch a [list of nested or transformed components](https://github.com/vv-monsalve/kufam/blob/QA-Kufam/sources/List-of-Nested-Transform-Components.docx) made with one local script in progress.

**Comment by arturschmal** [comment]
The decomposing of nested components has quite an impact on the benefits of using components during the editing stage. It would mean to rebuild quite some characters if the base shape is changed. Would it be better to address this in the build script as post-processing?

Another question is which component should be decomposed? `onefifth` is build from `one.numr` and `five.numr` as components, which in turn are components of `oneinferior` and `fiveinferior`. Should `onefifth` be decomposed in it's entirety or only the `.numr` glyphs? I would say the latter but maybe I'm wrong.

**Comment by arturschmal** [comment]
I'm opening this issue again because of [this result](https://github.com/originaltype/kufam/issues/16#issuecomment-769026120).

@vv-monsalve Are there other options for un-nesting nested components without touching the source files?
