### ISSUE TITLE
Arabic glyph set in Italic masters

### ISSUE THREAD

**Issue by davelab6** [originaltype/kufam#2]
There is set of italic masters for Latin. How is the arabic handled in those masters today? Are there arabic glyphs only existing in the Roman masters?

**Comment by vv-monsalve** [comment]
Reviewing the masters that are in the repository today:
Roman Masters do have Arabic glyphs, Italic Masters don't.
This is the Arabic character set status:
![Kufam_Arabic](https://user-images.githubusercontent.com/48698976/62788501-a18beb00-ba8c-11e9-84f5-2335c4e36832.png)

**Comment by davelab6** [comment]
Alas! A year later I realize that I didn't reply to this. 

https://github.com/google/fonts/blob/master/CONTRIBUTING.md has stated since 2015,

> All font files within the family must have the same Unicode character set (unencoded glyphs can differ)

The Google Fonts API **requires** that the character set be the same across all styles, and so we can't publish Kufam until this is sorted. 

Since "italic" is a euro-centric concept, I propose simply duplicating the Arabic in the Roman, so that nothing visually happens to the arabic when italic is applied.
