### ISSUE TITLE
Kufam fixes needed after QA

### ISSUE THREAD

**Issue by vv-monsalve** [originaltype/kufam#3]
After first QA's were done, these are the main topics to check/solve:

### Kerning

> ⚠ WARN: Does GPOS table have kerning information?

The Kufam roman master lacks a kerning table. 
**Please create or provide it on the file.**

### Amount of contours

> ⚠ WARN: Check if each glyph has the recommended amount of contours.

Some of them were easily found on masters Glyphs file Eg. ogonekcomb.case doesn't have an anchor and should go up to reach the stem (see Aogonek). Others were found after checking .ttf files, where some extra contours appeared after fonts were exported. Eg. checking character 'a', corner produced 2 more contours on the black weight
**Please check the detail on QA8 report (link below on text)**

### Vendor ID
⚠ WARN: Checking OS/2 achVendID.
**Please provide one [ID](https://docs.microsoft.com/en-us/typography/vendors/)**

### Family Name

> ⚠ WARN The combined length of family and style exceeds 27 chars in the following 

The name in original Glyphs file doesn't fit the standards. There is a new Glyphs file where one Family Name was suggested, it keeps it short enough to avoid common length family issues. Following QA1 this, among other fixes was done (eg. 'a' contour fixed) to reduce Fails and Warns from QA. 

QA1 [(link)](https://github.com/vv-monsalve/kufam/blob/QA-Kufam/Fonts_ttf/qaKufamR1/Fontbakery/report.md) reported 31 Fails and 36 Warns. After changes on file, they were reduced on QA8 [(link)](https://github.com/vv-monsalve/kufam/blob/QA-Kufam/Fonts_ttf/qaKufamR8/Fontbakery/report.md) to 4 - 21 respectively. 

Main Warns remaining are related to the first topics mentioned above.
Please take a look at the files and let me know how do you prefer to continue with the process.

**Comment by vv-monsalve** [comment]
**Updates:**

- Missing kerning table: The file in the original repository lacks a kerning table. Please check if you have a copy on a local file that can be included.
- Amount of contours: Please check the last FontBakery report and tell us how do you want to proceed. [Link to report](https://github.com/vv-monsalve/kufam/blob/QA-Kufam/Fonts/TTF/qaKufam10/Fontbakery/report.md)
- Family Name: This item was solved.

**Comment by vv-monsalve** [comment]
Some of the amount of contour issues are likely due to interpolation problems between chosen components.
**E.g. nj 01CC:**
This is a composed glyph made with n and j, where j is likewise made of jdotless and _par.dot. 
In Glyphs source file it seems to be ok
![Screen Shot 2019-08-23 at 13 27 42](https://user-images.githubusercontent.com/48698976/63615215-67513c00-c5aa-11e9-8faf-184562fd9f5d.png)
But after Instances are exported, there are some mix-up results. It appears to be some conflict between them.
![Screen Shot 2019-08-23 at 13 34 25](https://user-images.githubusercontent.com/48698976/63615341-beefa780-c5aa-11e9-9e47-d85840e2e3d4.png)
Black
![Screen Shot 2019-08-23 at 13 27 35](https://user-images.githubusercontent.com/48698976/63615353-c8790f80-c5aa-11e9-8ded-7f1236ee1423.png)
regular

- - - -

There are also other parts that seem to have interpolation issues

![Screen Shot 2019-08-23 at 13 22 09](https://user-images.githubusercontent.com/48698976/63615835-dda26e00-c5ab-11e9-86f4-d9b15f26ce7e.png)

![Screen Shot 2019-08-23 at 13 22 21](https://user-images.githubusercontent.com/48698976/63615841-e2672200-c5ab-11e9-9b0a-791f6080c8ed.png)

**Comment by arturschmal** [comment]
I'm not experiencing any interpolation problems with the characters mentioned in the report. When I export the instances ttf's from the Glyphs files there seems to be no mix.
